trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'
  appName: 'Tailspin.SpaceGame.Web'
  buildProjects: '**/*.csproj'
  solution: 'Tailspin.SpaceGame.Web.sln'
  
stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'

    strategy:
      matrix:
        linux-18.04: 
          imageName: 'ubuntu-18.04'

    pool:
      vmImage: $(imageName)
      demands:
      - npm

    variables:
      dotnetSdkVersion: '3.1.x'
     

    steps:
    - script: 'echo "$(Build.ArtifactStagingDirectory) | $(Build.DefinitionName) | $(Build.BuildId) | $(Build.BuildNumber)"'
      displayName: 'Write build info'
    - script: 'ls -R'
      displayName: 'Write build info'

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: sdk
        version: $(dotnetSdkVersion)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/PressTrust/Bin'
        zipAfterPublish: false

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)/PressTrust/Bin/s'
        contents: '**' 
        targetFolder: '$(Build.ArtifactStagingDirectory)/PressTrust/Bin'

    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/PressTrust/Bin/s'
        Contents: '**/*' 
        RemoveSourceFolder: true

    - script: 'ls -R'
      displayName: 'Write build info'

    - script: 'ls -R $(Build.ArtifactStagingDirectory)'
      displayName: 'Write build info'


    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      condition: succeeded()
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: drop